# -*- coding: utf-8 -*-
"""practicee

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1naMi_VsFgLeDtrn6dlaHxZ-UtrgqJbHW
"""

# Write a for loop to calculate the factorial of a number provided by the user.
n=int(input())
factorial=1
for i in range(1,n+1):
  factorial*=i
print(factorial)

# program to find the first duplicate value in a list
a = [2, 3, 4, 5, 2, 6, 4]

b = set()
for i in a:
    if i in b:
        print("First duplicate:", i)
        break
    b.add(i)
else:
    print("No duplicates found")

# Write a while loop that asks the user to enter a number and stops when the number is 0.
n=None
while n!=0:
  n=int(input())
  if n==0:
     print(f'{n}')

n=None
sum=0
while n!=0:
  n=int(input())
  sum+=n
print(sum)

# Write a for loop to iterate over a list of strings and print each string in uppercase.
a=['hello','shhs','abc']
for i in a:
  print(i.upper())

# Write a while loop to reverse a number provided by the user.
a=int(input())
rev=0
temp=a
while a>0:
  rev=rev*10+a%10
  a=a//10
print(rev)

# Write a for loop to print the Fibonacci sequence up to n terms, where n is provided by the user.
n=int(input())
a,b=0,1
print(a,b)
for i in range(1,n+1):
 c=a+b
 print(c)
 a,b=b,c

# Write a for loop that iterates over a dictionary and prints the key-value pairs in the format key:value.
a={'name':'abc','class':'bca','roll no':321}
for key,value in a.items():
  print(key,value)

# Write a while loop to sum the digits of a positive integer provided by the user.
a=int(input())
sum=0
rev=0
while a>0:
  rem=a%10
  a=a//10
  sum+=rem
print(sum)

# Write a for loop to print all prime numbers between 2 and 50.
for i in range(2,51):
  for j in range(2,i):
    if i%j==0:
      break
  else:
      print(i)

# Write a for loop to reverse a string provided by the user without using built-in functions.
a='hello'
rev=''
for char in a:
  rev=char+rev
print(rev)

# reverse using .join
a='hello'
b=''.join(reversed(a))
print(b)

#reverse using slicing
a='hello'
b=a[::-1]
print(b)

# Given a list of words, write a for loop to find the longest word and its length.
a=['anita','naresh','mahender','santosh']
longest_word=""
longest_length=0
for word in a:
  if len(word) > longest_length:
   longest_word= word
   longest_length=len(word)
print(longest_word,longest_length)

# 1. Using a for loop, iterate over a list of strings and print only those that start with a vowel.
w='aeiouAEIOU'
list=['anita','Ishita','lakshita','sangita','nikta']
for i in list:
  if i[0] in w:
    print(i)

#2.Write a while loop that calculates the product of all even numbers between 1 and 20
n=1
while n<20:
  if n%2==0:
    print(n)
    n+=1

# 3. Using a for loop, print the multiplication table of 7.
n=7
for i in range(1,11):
  print(i*n)

# 4. Write a while loop that continuously takes user input and adds it to a list until the user enters
# 'stop'.
n=None
while n!=0:
  n=int(input())

# 5. Create a for loop that iterates over a list of numbers and prints the sum of squares of even
# numbers
a=[2,4,3,5,7]
sum=0
for i in a:
  if i%2==0:
    sum+=i*i
    print(sum)

# 6. Using a while loop, calculate the factorial of a number provided by the user.
a=int(input())
factorial=1
while a>0:
  factorial=factorial*a
  a-=1
print(factorial)

# 7. Write a for loop that iterates over two lists simultaneously and prints the sum of corresponding
# elements.
a=[2,3,4,5]
b=[4,3,3,2]
sum=0
for i,j in zip(a,b):
  sum=i+j
  print(sum)

# 8. Create a while loop that reverses the digits of a number provided by the user.
a=int(input())
rev=0
while a>0:
  rev=rev*10+a%10
  a=a//10
print(rev)

# 9. Using a for loop, iterate through a list and create a new list containing the squares of only the odd
# numbers
a=[2,3,4,5,6]
b=[]
for i in a:
  if i%2!=0:
    b.append(i*i)
print(b)

# 10.Write a while loop to find the smallest prime number greater than a given number n
n=1
while n > 0:

"""**Functions**"""

# Write a function greet() that prints 'Hello, World!' when called.
def greet():
 return 'Hello,World'
greet()

# Create a function add_numbers(a, b) that returns the sum of two numbers.
def add_numbers(a, b):
  return a+b
add_numbers(2,3)

# Write a function is_even(num) that checks whether a given number is even and returns True or
# False.
def is_even(num):
   if num%2==0:
     return True
   else:
    return False
is_even(2)

# Define a function square(x) that returns the square of a number.
def square(x):
  return x*x
square(2)

# Create a function print_name(name) that takes a string and prints 'Your name is [name]'
def print_name(name):
  return f'Your name is {name}'
print_name('Anita')

# Write a function multiply(x, y) that multiplies two numbers and returns the result.
def multiply(x,y):
  return x*y
multiply(2,3)

# Create a function max_of_two(a, b) that returns the larger of two numbers.
def max_of_two(a, b):
  if a>b:
    return a
  else:
    return b
max_of_two(3,5)

# Write a function factorial(n) that returns the factorial of a number n.
def factorial(n):
  if n==0 or n==1:
    return 1
  else:
   return n*factorial(n-1)
factorial(5)

# Define a function count_vowels(s) that counts and returns the number of vowels in a given string.
def count_vowels(s):
  v='aeiouAEIOU'
  count=0
  for i in s:
    if i in v:
     count+=1
  return count
count_vowels('anitA')

# Write a function reverse_string(s) that takes a string and returns it reversed.
def reverse_string(s):
  r=''
  for i in s:
    r=i+r
  return r
reverse_string('anit')

# Create a function is_palindrome(word) that checks if a given word is a palindrome (reads the same
# backward as forward).
def is_palindrome(s):
 r=''
 for i in s:
    r=i+r
    if r==s:
     return True
    else:
      return False
is_palindrome('helo')

# Write a function fahrenheit_to_celsius(f) that converts a temperature from Fahrenheit to Celsius.
def fahrenheit_to_celsius(f):
  return 5/9*(f-32)
fahrenheit_to_celsius(90)

# Define a function sum_of_list(lst) that returns the sum of all elements in a list.
def sum_of_list(lst):
  sum=0
  for i in lst:
    sum+=i
  print(sum)
sum_of_list([1,2,3,4,5])

# Create a function find_min(lst) that returns the smallest number in a list.
def find_min(lst):
  for i in lst:
   return min(i)
find_min([1,2,3])

"""RANDOM NUMBER FIND"""

import random
num=random.random()      # Generates a number between 0 and 1
print(num)

import random
num=random.randint(1,100)    # Generates an integer between 1 and 10 (inclusive)
print(num)

num = random.uniform(1.5, 3.5)  # Generates a float between 1.5 and 3.5
print(num)

num = random.randrange(0, 100, 5)  # Generates a number from 0 to 100, stepping by 5
print(num)

my_list = [10, 20, 30, 40, 50]
num = random.choice(my_list)  # Picks a random element from the list
print(num)

for i in range(1,11):
  for j in range(2,i):
    if i%j==0:
      break
  else:
     print(i)

# Write a Python Program to Check Prime Number
n=int(input())
for i in n:
  for

def fibonacci(n):
  if n<=0:
    return 0
  elif n==1:
    return 1
  else:
    return fibonacci(n-1)+fibonacci(n-2)
for i in range(10):
  print(fibonacci(i))



weight=float(input())
height=float(input())
bmi=weight/(height*height)
print(bmi)

a=['anita','gjsh','bdbb']
a.sort()
print(a)